# Generated by Django 3.2.7 on 2022-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60, verbose_name='Место положение')),
                ('weather', models.CharField(max_length=60, verbose_name='Погода')),
                ('date', models.DateField(verbose_name='Дата')),
                ('temperature', models.CharField(max_length=10, verbose_name='Температура')),
                ('weather_feel', models.CharField(max_length=60, verbose_name='По ощущению')),
                ('parse_date', models.DateTimeField(verbose_name='Время парсинга')),
            ],
            options={
                'verbose_name': 'Погода',
                'verbose_name_plural': 'Погода',
            },
        ),
    ]
